/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.journal;

class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
